### ISSUE TITLE
No network, please log in again

### ISSUE THREAD

**Issue by weqasds** [WeedwackerPS/Weedwacker#5]
When I play with the release version, I find that after entering the game there is a white screen, after a while it says that there is no network, please reconnect, and ru'xia is found in the program ...

[22-11-29 12:14:23]<Connection.cs:ProcessMessageAsync> Object reference not set to an instance of an object.
[22-11-29 12:14:23]<Logger.cs:WriteErrorLine>    at Weedwacker.GameServer.Systems.Player.Player.SendPacketAsync(BasePacket packet) in F:\genshin_weak\Weedwacker\src\GameServer\Systems\Player\Player.cs:line 338
   at Weedwacker.GameServer.Systems.Avatar.Avatar.UnequipWeapon(Boolean notifyClient) in F:\genshin_weak\Weedwacker\src\GameServer\Systems\Avatar\Avatar.cs:line 332
   at Weedwacker.GameServer.Systems.Avatar.Avatar.EquipWeapon(WeaponItem item, Boolean notifyClient) in F:\genshin_weak\Weedwacker\src\GameServer\Systems\Avatar\Avatar.cs:line 266
   at Weedwacker.GameServer.Systems.Inventory.InventoryManager.EquipWeapon(UInt64 avatarGuid, UInt64 equipGuid) in F:\genshin_weak\Weedwacker\src\GameServer\Systems\Inventory\InventoryManager.cs:line 338
   at Weedwacker.GameServer.Systems.Inventory.WeaponTab.OnLoadAsync(Player owner, InventoryManager inventory) in F:\genshin_weak\Weedwacker\src\GameServer\Systems\Inventory\SubInventories\WeaponTab.cs:line 30
   at Weedwacker.GameServer.Systems.Inventory.InventoryManager.OnLoadAsync(Player owner) in F:\genshin_weak\Weedwacker\src\GameServer\Systems\Inventory\InventoryManager.cs:line 380
   at Weedwacker.GameServer.Database.DatabaseManager.GetInventoryByPlayerAsync(Player owner) in F:\genshin_weak\Weedwacker\src\GameServer\Database\DatabaseManager.cs:line 213
   at Weedwacker.GameServer.Database.DatabaseManager.GetPlayerByAccountUidAsync(String uid) in F:\genshin_weak\Weedwacker\src\GameServer\Database\DatabaseManager.cs:line 159
   at Weedwacker.GameServer.Packet.Recv.HandleGetPlayerTokenReq.HandleAsync(Connection session, Byte[] header, Byte[] payload) in F:\genshin_weak\Weedwacker\src\GameServer\Packet\Recv\HandleGetPlayerTokenReq.cs:line 22
   at Weedwacker.GameServer.Connection.HandlePacketAsync(UInt16 opcode, Byte[] header, Byte[] payload) in F:\genshin_weak\Weedwacker\src\GameServer\Connection.cs:line 298
   at Weedwacker.GameServer.Connection.ProcessMessageAsync(Memory`1 data) in F:\genshin_weak\Weedwacker\src\GameServer\Connection.cs:line 233

**Comment by akatatsu27** [comment]
did you perhaps create a different account and use the same name for the traveller?

**Comment by akatatsu27** [comment]
Unable to reproduce. Can you provide more details/steps to reproduce?

**Comment by weqasds** [comment]
In VS2022 I use release mode to generate the program, and after running the service according to the steps, I open the game, after entering the door, there will be a long white screen, and then the above error appears

**Comment by akatatsu27** [comment]
> In VS2022 I use release mode to generate the program, and after running the service according to the steps, I open the game, after entering the door, there will be a long white screen, and then the above error appears
It doesn't happen in the DEBUG build? Debug just has more logs.
Are both servers and the client in the same machine (localhost)?
Have you successfully started the game before?
Did you change anything in the config files?
The above error message indicates at some previous point you had created a character, meaning you had successfully went through the opening cutscene.
Did you modify the mongodb database?
Did you try deleting the database entirely?

**Comment by weqasds** [comment]
> 

As far as I know, this doesn't appear in debug mode

**Comment by weqasds** [comment]
> > 在VS2022中我使用发布模式生成程序，按照步骤运行服务后，我打开游戏，进门后会出现长长的白屏，然后出现上面的错误
> 
> 它不会在调试版本中发生吗？调试只是有更多的日志。服务器和客户端是否在同一台计算机（本地主机）中？你之前成功启动游戏了吗？您是否更改了配置文件中的任何内容？上面的错误消息表明您在之前的某个时间点创建了一个角色，这意味着您已成功完成开场过场动画。您是否修改了 mongodb 数据库？您是否尝试完全删除数据库？

And I haven't modified the database

**Comment by tamilpp25** [comment]
I have just now tested with a fresh clone of this project, reset database and running on release mode and it works perfectly fine for me.

**Comment by weqasds** [comment]
> 我刚刚用这个项目的新克隆进行了测试，重置数据库并在发布模式下运行，它对我来说非常好用。
ok，thanks
